# Generated by Django 6.0.4 on 2026-04-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип посылки',
                'verbose_name_plural': 'Типы посылок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название посылки')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)')),
                ('content_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость содержимого (руб)')),
                ('session_id', models.CharField(db_index=True, max_length=100, verbose_name='ID сессии пользователя')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость доставки (руб)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parcel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='delivery.parceltype', verbose_name='Тип посылки')),
            ],
            options={
                'verbose_name': 'Посылка',
                'verbose_name_plural': 'Посылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
