# Generated by Django 6.0.4 on 2026-04-21 16:15

from django.db import migrations


def add_parcel_types(apps, schema_editor):
    """Добавляем начальные типы посылок"""
    ParcelType = apps.get_model('delivery', 'ParcelType')

    parcel_types = [
        {'name': 'Одежда'},
        {'name': 'Электроника'},
        {'name': 'Разное'},
    ]

    for parcel_type in parcel_types:
        ParcelType.objects.create(**parcel_type)


def remove_parcel_types(apps, schema_editor):
    """Удаляем типы посылок при откате"""
    ParcelType = apps.get_model('delivery', 'ParcelType')
    ParcelType.objects.filter(
        name__in=['Одежда', 'Электроника', 'Разное']
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('delivery', '0001_initial'),  # Зависит от первой миграции
    ]

    operations = [
        migrations.RunPython(add_parcel_types, remove_parcel_types),
    ]